# Definitions for jobs that run periodically.  For details on the format, see
# `taskcluster/taskgraph/cron/schema.py`.  For documentation, see
# `taskcluster/docs/cron.rst`.
---

jobs:
    - name: nightly
      job:
          type: decision-task
          treeherder-symbol: Nd
          target-tasks-method: nightly
      when:
          - {hour: 6, minute: 0}
    # Cannot name the following entry "bump-android-component" because the full hookId is larger
    # than 64 characters. For more details see: https://phabricator.services.mozilla.com/D67443
    - name: bump-android-comp
      job:
          type: decision-task
          treeherder-symbol: bump-ac
          target-tasks-method: bump_android_components
      when: [{hour: 16, minute: 0}]
