queue_rules:
  - name: default
    conditions:
      - status-success=pr-complete
    merge_method: rebase
    branch_protection_injection_mode: none
pull_request_rules:
  - name: MickeyMoz - Auto Merge
    conditions:
      - author=MickeyMoz
      - status-success=pr-complete
      - files=gradle/libs.versions.toml
    actions:
      review:
        type: APPROVE
        message: MickeyMoz 💪
      queue:
        name: default
  - name: Needs landing - Merge
    conditions:
      - status-success=pr-complete
      - label=needs landing
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
merge_queue:
  max_parallel_checks: 1
